# Generated by Django 3.2.8 on 2023-11-16 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rolex',
            fields=[
                ('goLive', models.CharField(blank=True, max_length=200, null=True)),
                ('nickName', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('titleBackend', models.CharField(blank=True, max_length=200, null=True)),
                ('brand', models.CharField(blank=True, max_length=200, null=True)),
                ('model', models.CharField(blank=True, max_length=200, null=True)),
                ('ref', models.CharField(blank=True, max_length=200, null=True)),
                ('strap', models.CharField(blank=True, max_length=200, null=True)),
                ('dial', models.CharField(blank=True, max_length=200, null=True)),
                ('imageAmount', models.CharField(blank=True, max_length=200, null=True)),
                ('strapMaterial', models.CharField(blank=True, max_length=200, null=True)),
                ('strapColour', models.CharField(blank=True, max_length=200, null=True)),
                ('strapClasp', models.CharField(blank=True, max_length=200, null=True)),
                ('dialSize', models.CharField(blank=True, max_length=200, null=True)),
                ('numberMarkers', models.CharField(blank=True, max_length=200, null=True)),
                ('hands', models.CharField(blank=True, max_length=200, null=True)),
                ('caseMaterial', models.CharField(blank=True, max_length=200, null=True)),
                ('bezel', models.CharField(blank=True, max_length=200, null=True)),
                ('bezelStyle', models.CharField(blank=True, max_length=200, null=True)),
                ('bezelDirection', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.IntegerField(blank=True, default=0, null=True)),
                ('caliber', models.CharField(blank=True, max_length=200, null=True)),
                ('movement', models.CharField(blank=True, max_length=200, null=True)),
                ('powerReserve', models.CharField(blank=True, max_length=200, null=True)),
                ('waterResistant', models.CharField(blank=True, max_length=200, null=True)),
                ('numberOfJewels', models.CharField(blank=True, max_length=200, null=True)),
                ('crystal', models.CharField(blank=True, max_length=200, null=True)),
                ('gender', models.CharField(blank=True, max_length=200, null=True)),
                ('box', models.CharField(blank=True, max_length=200, null=True)),
                ('card', models.CharField(blank=True, max_length=200, null=True)),
                ('condition', models.CharField(blank=True, max_length=200, null=True)),
                ('warranty', models.CharField(blank=True, max_length=200, null=True)),
                ('availble', models.CharField(blank=True, max_length=200, null=True)),
                ('descriptionMobile', models.TextField(blank=True, null=True)),
                ('descriptionDesktop', models.TextField(blank=True, null=True)),
                ('descriptionSmall', models.TextField(blank=True, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('numReviews', models.IntegerField(blank=True, default=0, null=True)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
